
export enum TextActionTypes {
  INSERT_TEXT = 'INSERT_TEXT',
  SET_FONT_SIZE = 'SET_FONT_SIZE',
  SET_FONT_COLOR = 'SET_FONT_COLOR',
  SET_FONT_FAMILY = 'SET_FONT_FAMILY',
  SET_FONT_WEIGHT = 'SET_FONT_WEIGHT',
  NEW_CARD_TEXT = 'NEW_CARD_TEXT'
  
}
